### PR TITLE
Remove dependancy on hr_expense_line_supplier. Add partner field, needed it in dependancy.

### PR DESCRIPTION
**Pull request by mathben**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Needs migration scripts for openupgrade

**Comment by pedrobaeza** [comment]
Better to be made with standard upgrade mechanism.

**Comment by bwrsandman** [comment]
Yes, that's what I meant, but it's also a reminder that hr_expense_line_supplier needs to be added to openupgrade as a module which no longer exists in 7.0

**Comment by max3903** [comment]
I just migrated hr_expense_line_supplier to version 7.0. Dependency can be kept.

**Comment by bwrsandman** [comment]
@max3903 where is it? I don't see it

**Comment by max3903** [comment]
It's here:
https://github.com/OCA/l10n-canada/pull/15

**Comment by bwrsandman** [comment]
Is that the best place to put that module? I find it strange that account_edge modules would depend on canada modules

**Comment by max3903** [comment]
Accountedge is a canadian accounting software...

**Comment by bwrsandman** [comment]
~~Depends on https://github.com/OCA/l10n-canada/pull/15~~

**Comment by foutoucour** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
